spanflug/urls.py
from django.contrib import admin
from django.urls import path
from doc_app.views import WelcomeView, LoginView, LogutView, AddUserView, DashboardView, DocumentCreateView, \
    DocumentView, AttributesCreateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', WelcomeView.as_view(), name='welcome'),
    path('login', LoginView.as_view(), name='login-view'),
    path('logout', LogutView.as_view(), name='logout-view'),
    path('register', AddUserView.as_view(), name='add-user-form'),
    path('dashboard', DashboardView.as_view(), name='dashboard'),
    path('add-document', DocumentCreateView.as_view(), name='add-document'),
    path('document-view/<int:document_id>', DocumentView.as_view(), name='document-view'),
    path('add-attributes', AttributesCreateView.as_view(), name='add-attributes'),
]

doc_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Document(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(null=True)
    path = models.FileField(upload_to='documents/%Y/%m/%d')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class Attributes(models.Model):
    key = models.CharField(max_length=255)
    value = models.TextField()
    document = models.ForeignKey(Document, on_delete=models.CASCADE)

doc_app/forms.py
from django.contrib.auth.models import User
from django import forms


class AddUserForm(forms.Form):
    login = forms.CharField(max_length=64)
    password = forms.CharField(max_length=64, widget=forms.PasswordInput)
    repeatPassword = forms.CharField(max_length=64, widget=forms.PasswordInput)
    first_name = forms.CharField(max_length=64)
    last_name = forms.CharField(max_length=64)
    email = forms.EmailField()

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        repeat_password = cleaned_data.get('repeatPassword')
        login = cleaned_data.get('login')
        if password != repeat_password:
            raise forms.ValidationError("Wrong Password!")
        try:
            user = User.objects.get(username=login)
        except User.DoesNotExist:
            return None
        if user.username == login:
            raise forms.ValidationError("Given login already in Data Base")


class LoginForm(forms.Form):
    login = forms.CharField(max_length=64)
    password = forms.CharField(max_length=64, widget=forms.PasswordInput)


class AddDocumentForm(forms.Form):
    name = forms.CharField(max_length=255)
    description = forms.Textarea()
    path = forms.FileField()


class AddAttributeForm(forms.Form):
    key = forms.CharField(max_length=255)
    value = forms.TextInput()

doc_app/views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.views import View
from django.shortcuts import render, redirect

from doc_app.models import Document, Attributes
from doc_app.forms import LoginForm, AddUserForm, AddDocumentForm, AddAttributeForm


# Create your views here.


class WelcomeView(View):
    def get(self, request):
        return render(request, 'views/welcome.html')


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        return render(request, 'forms/login_form.html', {'form': form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['login']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('dashboard')
            else:
                return HttpResponse('Logging error')


class LogutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('/')


class AddUserView(View):
    def get(self, request):
        form = AddUserForm()
        return render(request, 'forms/add_user_form.html', {'form': form})

    def post(self, request):
        form = AddUserForm(request.POST)
        if form.is_valid():
            login_user = form.cleaned_data['login']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            User.objects.create_user(username=login_user,
                                     email=email,
                                     password=password,
                                     first_name=first_name,
                                     last_name=last_name)
            return redirect('/')
        else:
            return render(request, 'forms/add_user_form.html', {'form': form})


class DashboardView(LoginRequiredMixin, View):
    def get(self, request):
        user = User.objects.get(id=request.user.id)
        documents = Document.objects.filter(user=user.id)
        return render(request, 'views/dashboard.html', {'documents': documents})


class DocumentCreateView(LoginRequiredMixin, View):

    def get(self, request):
        form = AddDocumentForm()
        return render(request, 'forms/add_document_form.html', {'form': form})

    def post(self, request):
        form = AddDocumentForm(request.POST, request.FILES)
        if form.is_valid():
            document = Document(
                name=request.POST['name'],
                path=request.FILES['path'],
                user=request.user)
            document.save()

            return redirect('dashboard')
        else:
            return render(request, 'forms/add_document_form.html', {'form': form})


class DocumentView(View):

    def get(self, request, document_id):
        document = Document.objects.get(id=document_id)
        return render(request, 'views/document-view.html', {'document': document})


class AttributesCreateView(View):

    def get(self, request):
        form = AddAttributeForm()
        return render(request, 'forms/add_attributes_form.html')

    def post(self, request):
        form = AddAttributeForm(request.POST)
        if form.is_valid():
            pass

doc_app/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Bartlomiej Stoklosa">
    <title>{% block title %}{% endblock %}| Document manager</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
{% if user.is_authenticated %}
    <p>Welcome {{ user }}</p>
{% endif %}
{% if user.is_authenticated %}
    <a href="{% url 'logout-view' %}">Logout</a>
{% else %}
    <a href="{% url 'login-view' %}">Login</a>
{% endif %}

{% if user.is_authenticated %}
{% else %}
    <a href="{% url 'add-user-form' %}">
        Register User
    </a>
{% endif %}

{% block content %}
{% endblock %}

</body>
</html>

doc_app/templates/forms/add_attributes_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <form action="#" method="post">
        {% csrf_token %}
        {{ form.key.label }}<br>
        {{ form.key }}<br>
        {{ form.key.errors }}<br>
        {{ form.value.label }}<br>
        {{ form.value }}<br>
        {{ form.value.errors }}<br>
        <input type="submit" value="Save">
    </form>
{% endblock %}

doc_app/templates/forms/add_document_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <form action="#" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.name.label }}<br>
        {{ form.name }}<br>
        {{ form.name.errors }}<br>
        {{ form.description.label }}<br>
        {{ form.description }}<br>
        {{ form.description.errors }}<br>
        {{ form.path.label }}
        {{ form.path }}
        {{ form.path.errors }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

doc_app/templates/forms/add_user_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <form action="#" method="post">
        {% csrf_token %}
        {{ form.login.label }}<br>
        {{ form.login }}<br>
        {{ form.login.errors }}<br>
        {{ form.password.label }}<br>
        {{ form.password }}<br>
        {{ form.password.errors }}<br>
        {{ form.repeatPassword.label }}<br>
        {{ form.repeatPassword }}<br>
        {{ form.repeatPassword.errors }}<br>
        {{ form.first_name.label }}<br>
        {{ form.first_name }}<br>
        {{ form.first_name.errors }}<br>
        {{ form.last_name.label }}<br>
        {{ form.last_name }}<br>
        {{ form.last_name.errors }}<br>
        {{ form.email.label }}<br>
        {{ form.email }}<br>
        {{ form.email.errors }}<br>
        <input type="submit" value="Save">
    </form>
{% endblock %}

doc_app/templates/forms/login_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <form action="#" method="post">
        {% csrf_token %}
        {{ form.login.label }}<br>
        {{ form.login }}<br>
        {{ form.login.errors }}<br>
        {{ form.password.label }}<br>
        {{ form.password }}<br>
        {{ form.password.errors }}<br>
        <input type="submit" value="Login">
    </form>
{% endblock %}

doc_app/templates/views/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div>
        <a href="{% url 'add-document' %}">Add document</a>
    </div>
    <br>
    <div>
        <table>
            <thead>
            <tr>
                <th>#</th>
                <th>Document</th>
                <th>Description</th>
                <th>Created at</th>
                <th>Attributes</th>
            </tr>
            </thead>
            <tbody>
            {% for document in documents %}
                <tr>
                    <td>{{ document.id }}</td>
                    <td><a href="/document-view/{{ document.id }}">{{ document.name }}</a></td>
                    <td>{{ document.description }}</td>
                    <td>{{ document.created_at }}</td>
                    <td>
                        {% for attribute in document.attributes_set.all %}
                            <p>{{ attribute.key }}</p>
                            <p>{{ attribute.value }}</p>
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}

doc_app/templates/views/document-view.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <br>
    <div>
        <table>
            <thead>
            <tr>
                <th>#</th>
                <th>Document</th>
                <th>Description</th>
                <th>Created at</th>
                <th>Attributes</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ document.id }}</td>
                <td>{{ document.name }}</td>
                <td>{{ document.description }}</td>
                <td>{{ document.created_at }}</td>
                <td>
                    {% for attribute in document.attributes_set.all %}
                        <p>{{ attribute.key }}</p>
                        <p>{{ attribute.value }}</p>
                    {% endfor %}
                </td>
                <td>
                    <a href="{% url 'add-attributes' %}">Add attributes</a>
                </td>
            </tr>
            </tbody>
        </table>

    </div>
{% endblock %}

doc_app/templates/views/welcome.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    Welcome!
{% endblock %}